modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/Diamantino-Op/DiamantinoCraft-1.15.2"
displayURL="https://www.curseforge.com/minecraft/mc-mods/diamantinocraft"
#logoFile="examplemod.png"
credits="Diamantino Op"
authors="Diamantino Op"

[[mods]]
    modId="diamantinocraft"
    version="1.1.1"
    displayName="DiamantinoCraft"
    description='''
    '''

[[dependencies.diamantinocraft]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.diamantinocraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"