@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.diamantino.diamantinocraft.compat.jei;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;