@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.diamantino.diamantinocraft.block.electricfurnace;

import mezz.jei.api.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;