@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.diamantino.diamantinocraft.world.feature;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;