@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.diamantino.diamantinocraft.inventory;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;