@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.diamantino.diamantinocraft.block.solidifier;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;