@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.diamantino.diamantinocraft.block.generator.diesel;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;